# Generated by Django 5.2 on 2025-05-03 12:50

import uuid
from django.conf import settings
from django.db import migrations, models


def generate_invite_tokens(apps, schema_editor):
    Board = apps.get_model("boards", "Board")
    for board in Board.objects.all():
        board.invite_token = uuid.uuid4()
        board.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_board_created_at_board_owner_column_order_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Удаляем старое поле owner (если было)
        migrations.RemoveField(model_name="board", name="owner"),

        # Добавляем новое ManyToMany поле
        migrations.AddField(
            model_name="board",
            name="owners",
            field=models.ManyToManyField(
                related_name="boards", to=settings.AUTH_USER_MODEL
            ),
        ),

        # Добавляем поле invite_token временно без unique и с null=True
        migrations.AddField(
            model_name="board",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),

        # Заполняем токены
        migrations.RunPython(generate_invite_tokens),

        # Теперь делаем поле уникальным и обязательным
        migrations.AlterField(
            model_name="board",
            name="invite_token",
            field=models.UUIDField(unique=True),
        ),
    ]
