# Generated by Django 5.2 on 2025-05-04 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_remove_board_owner_board_invite_token_board_owners"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="order", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
