# Generated by Django 5.2 on 2025-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0005_task_order_alter_board_invite_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="order", field=models.IntegerField(default=0),
        ),
    ]
