# Generated by Django 5.2 on 2025-05-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0006_alter_task_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="order",),
    ]
