# Generated by Django 5.2 on 2025-05-07 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0008_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="last_opened",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
