# Generated by Django 5.2 on 2025-05-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0009_board_last_opened"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column", name="order", field=models.IntegerField(default=0),
        ),
    ]
